/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FramesFrame1RouteImport } from './routes/frames/frame1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesFrame1Route = FramesFrame1RouteImport.update({
  id: '/frames/frame1',
  path: '/frames/frame1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/frames/frame1': typeof FramesFrame1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/frames/frame1': typeof FramesFrame1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/frames/frame1': typeof FramesFrame1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/frames/frame1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/frames/frame1'
  id: '__root__' | '/' | '/frames/frame1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FramesFrame1Route: typeof FramesFrame1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/frame1': {
      id: '/frames/frame1'
      path: '/frames/frame1'
      fullPath: '/frames/frame1'
      preLoaderRoute: typeof FramesFrame1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FramesFrame1Route: FramesFrame1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
